# Generated by Django 2.2.4 on 2020-03-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'db_table': 'customer',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_no', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=100)),
                ('specification', models.SmallIntegerField(choices=[(1, '五斤'), (2, '十斤')])),
                ('image', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.SmallIntegerField(choices=[(-1, '已删除'), (0, '下架'), (1, '上架')])),
                ('description', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'product',
                'db_table': 'product',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_no', models.BigIntegerField()),
                ('product_num', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(-2, '已取消'), (-1, '待付款'), (0, '待发货'), (1, '已发货'), (2, '已收货')])),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deliver_type', models.SmallIntegerField(choices=[(0, '送货上门'), (1, '自提')], null=True)),
                ('is_pay', models.SmallIntegerField(choices=[(0, '未付款'), (1, '已支付')])),
                ('express_no', models.CharField(max_length=100, null=True)),
                ('payment_time', models.DateTimeField(null=True)),
                ('send_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='KiwiAdmin.Customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='KiwiAdmin.Product')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'db_table': 'order',
                'ordering': ['-create_time'],
            },
        ),
    ]
